name: Hello World Action
on:
  push:
    branches:
      - main
jobs:
  merge-job:
    runs-on: ubuntu-latest
    steps:
      - name: print hello world to summary
        run: echo "Hello World" >> $GITHUB_STEP_SUMMARY
