name: Greetings + Response

on:
  workflow_dispatch:

jobs:
  call_greetings:
    uses: ./.github/workflows/greetings.yml
    with:
      input_name: "Ben"
      english: true
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Goodbye"
