name: Test Dispatch Action
on:
  workflow_dispatch:
jobs:
  this-run:
    runs-on: ubuntu-latest
    steps:
      - name: clone to runner
        uses: actions/checkout@v3

      - name: run hi
        run: bash ./scripts/hi.sh
